function [ps, queryString] = queryForRunInformation()
% Query to get scenario id and config id
ps = 'query for scenario id, config id, and network id corresponding to a given run';
queryString = [...
    'SELECT estimation_runs.scenario_id, config_id, network_id ',...
    'FROM via.estimation_runs JOIN via.network_sets ',...
    'ON estimation_runs.scenario_id = network_sets.scenario_id ',...
    'WHERE run_number = ?'];