%%
%List of names for lid sets in listOfLinkIDs.m. This is loaded by the GUI
%in order to populate the drop down menu.
lidNames = {'lids10', ... 
            'lids15NBa', ...
            'lids15NBpaul', ...
            'lids15SBpaul', ... 
            'lids880NBa', ... 
            'lids280NB', ...
            'lids101NB_ssf', ...  
            'lids101NB_paloalto', ...
            'lids28', ...
            'lids880NBforBT', ...
            'lids880SBforBT',...
            'lids15SBforBT',...
            'lids15NBforBT',...
            'lids15NBmats', ...
            'lids15VictorvilleSBforBT',...
            'lids15VictorvilleNBforBT',...
            'lids15Victorville',...
            'lids880BT_NB',...
            'ORAlids880NBforBT',...
            'ORAlidsI15SB',...
            'ORAlidsI15SB-MainlineOnly',...
            'ORAlidsI15SBTesting',...
            'ORAlids880NBforBTOneThird',...
            'ORAlidsSmallNetwork28',...
            'I15Sv13',...
            'I15Sv56',...
            'I210Sc96',...
            'I210Sc91',...
            'I210Sc91ML',...
            'I210Sc91Ar',...
            'I210SmallNetwork',...
            'I210Sc96ML'};
